# Generated by Django 3.1.4 on 2021-01-20 13:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coremetric_app', '0003_auto_20210120_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentedOn',
            field=models.DateField(verbose_name=datetime.datetime(2021, 1, 20, 13, 28, 56, 341914, tzinfo=utc)),
        ),
    ]
