# Generated by Django 3.1.3 on 2021-01-21 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coremetric_app', '0005_auto_20210120_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentedOn',
            field=models.DateField(verbose_name=datetime.datetime(2021, 1, 21, 5, 25, 38, 596392, tzinfo=utc)),
        ),
    ]
