# Generated by Django 3.1.3 on 2021-02-20 08:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coremetric_app', '0006_auto_20210121_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentedOn',
            field=models.DateField(default=datetime.datetime(2021, 2, 20, 8, 28, 21, 754531, tzinfo=utc)),
        ),
    ]
